# Generated by Django 3.1.6 on 2021-04-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='userdefault.png', null=True, upload_to='profile_image_organization/')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('phonenumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='userdefault.png', null=True, upload_to='profile_image_user/')),
                ('donated', models.PositiveIntegerField(default=0)),
                ('phonenumber', models.CharField(max_length=12)),
                ('organizations', models.ManyToManyField(related_name='organization', to='donate.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.user')),
            ],
        ),
    ]
