# Generated by Django 3.1.6 on 2021-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20210414_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='description',
            new_name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
