# Generated by Django 3.1.6 on 2021-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20210414_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
