# Generated by Django 3.1.6 on 2021-04-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20210415_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='invoices/'),
        ),
    ]
