# Generated by Django 3.1.6 on 2021-04-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_transaction_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
