# Generated by Django 3.1.6 on 2021-04-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_auto_20210416_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
